# Generated by Django 4.0.1 on 2022-01-31 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medical_card.storage_backends
import welcome.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя и фамилия врача')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEstablishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя название лечебного учреждения')),
                ('address', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('site', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Пожалуйста добавьте область медицины')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_birthday_date', models.DateField(validators=[welcome.models.validate_even], verbose_name='Укажите вашу дату рождения')),
                ('registration_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCardInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_at', models.DateField(verbose_name='Дата проведения исследования')),
                ('title', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Краткое описание записи')),
                ('description', models.TextField(blank=True, default=None, max_length=600)),
                ('p_age', models.SmallIntegerField(default=1, verbose_name='Количество полных лет пациента на момент проведения исследования')),
                ('p_age_status', models.BooleanField(default=False)),
                ('doctors', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.doctors')),
                ('medical_Establishments', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.medicalestablishments')),
                ('medical_field', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.medicalfield')),
                ('medicine_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.medicinecard')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('upload', models.FileField(storage=medical_card.storage_backends.PrivateMediaStorage(), upload_to=welcome.models.upload_path_handler)),
                ('mci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.medicinecardinstance')),
            ],
        ),
    ]
