# Generated by Django 4.0.1 on 2022-01-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalestablishments',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Адрес лечебного учреждения'),
        ),
        migrations.AlterField(
            model_name='medicalestablishments',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название лечебного учреждения'),
        ),
        migrations.AlterField(
            model_name='medicalestablishments',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Телефон лечебного учреждения'),
        ),
        migrations.AlterField(
            model_name='medicalestablishments',
            name='site',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Сайт лечебного учреждения'),
        ),
    ]
