# Generated by Django 4.0.1 on 2022-01-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_alter_medicalestablishments_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinecardinstance',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=600, verbose_name='Полное описание записи'),
        ),
        migrations.AlterField(
            model_name='medicinecardinstance',
            name='doctors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.doctors', verbose_name='Лечащий врач'),
        ),
        migrations.AlterField(
            model_name='medicinecardinstance',
            name='medical_Establishments',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.medicalestablishments', verbose_name='Лечебное учреждение'),
        ),
        migrations.AlterField(
            model_name='medicinecardinstance',
            name='medical_field',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.medicalfield', verbose_name='Область медицины'),
        ),
    ]
