# Generated by Django 4.0.1 on 2022-02-21 09:33

from django.db import migrations, models
import medical_card.storage_backends
import welcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_alter_medicinecardinstance_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinecardinstance',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1000, verbose_name='Полное описание записи'),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='upload',
            field=models.FileField(storage=medical_card.storage_backends.PrivateMediaStorage(), upload_to=welcome.models.upload_path_handler, verbose_name='Загрузить документ'),
        ),
    ]
