# Generated by Django 4.0.1 on 2022-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_alter_medicinecardinstance_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalestablishments',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название лечебного учреждения'),
        ),
    ]
