# Generated by Django 4.0.1 on 2022-07-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_alter_medicalestablishments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinecardinstance',
            old_name='medical_Establishments',
            new_name='medical_establishments',
        ),
    ]
